### ISSUE TITLE
Doesn't work with python 3.12

### ISSUE THREAD

**Issue by rmetcalf9** [rmetcalf9/EllucianEthosPythonClient#4]
Error occured with python 3.12 due to versioneer needing to be updated.

**Comment by rmetcalf9** [comment]
Output when trying to install in python 3.12
```
(venv) PS C:\off_drive\hd\git\EllucianEthosApiUi> python -m pip install EllucianEthosPythonClient
Collecting EllucianEthosPythonClient
  Using cached EllucianEthosPythonClient-0.2.17.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      C:\Users\RobertMetcalf\AppData\Local\Temp\pip-install-4w2jg2gs\ellucianethospythonclient_15b527a81add42069258d40beb98d7fe\versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "C:\off_drive\hd\git\EllucianEthosApiUi\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\off_drive\hd\git\EllucianEthosApiUi\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\off_drive\hd\git\EllucianEthosApiUi\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel      
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\RobertMetcalf\AppData\Local\Temp\pip-build-env-tp907u6g\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel       
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\RobertMetcalf\AppData\Local\Temp\pip-build-env-tp907u6g\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\RobertMetcalf\AppData\Local\Temp\pip-build-env-tp907u6g\overlay\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\RobertMetcalf\AppData\Local\Temp\pip-build-env-tp907u6g\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 22, in <module>
        File "C:\Users\RobertMetcalf\AppData\Local\Temp\pip-install-4w2jg2gs\ellucianethospythonclient_15b527a81add42069258d40beb98d7fe\versioneer.py", line 1480, in get_version   
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "C:\Users\RobertMetcalf\AppData\Local\Temp\pip-install-4w2jg2gs\ellucianethospythonclient_15b527a81add42069258d40beb98d7fe\versioneer.py", line 1412, in get_versions  
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\RobertMetcalf\AppData\Local\Temp\pip-install-4w2jg2gs\ellucianethospythonclient_15b527a81add42069258d40beb98d7fe\versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


```

**Comment by rmetcalf9** [comment]
After update still getting the error
```
(venv) PS C:\off_drive\hd\git\EllucianEthosApiUi> python -m pip install EllucianEthosPythonClient
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/ellucianethospythonclient/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/ellucianethospythonclient/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/ellucianethospythonclient/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/ellucianethospythonclient/
Collecting EllucianEthosPythonClient
  Downloading EllucianEthosPythonClient-0.2.18.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      C:\Users\RobertMetcalf\AppData\Local\Temp\pip-install-nx4om0m6\ellucianethospythonclient_c34c911c0cc54dbea664d7bd9670bfee\versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "C:\off_drive\hd\git\EllucianEthosApiUi\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\off_drive\hd\git\EllucianEthosApiUi\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\off_drive\hd\git\EllucianEthosApiUi\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel      
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\RobertMetcalf\AppData\Local\Temp\pip-build-env-vy82bnvy\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel       
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\RobertMetcalf\AppData\Local\Temp\pip-build-env-vy82bnvy\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\RobertMetcalf\AppData\Local\Temp\pip-build-env-vy82bnvy\overlay\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\RobertMetcalf\AppData\Local\Temp\pip-build-env-vy82bnvy\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 22, in <module>
        File "C:\Users\RobertMetcalf\AppData\Local\Temp\pip-install-nx4om0m6\ellucianethospythonclient_c34c911c0cc54dbea664d7bd9670bfee\versioneer.py", line 1480, in get_version   
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "C:\Users\RobertMetcalf\AppData\Local\Temp\pip-install-nx4om0m6\ellucianethospythonclient_c34c911c0cc54dbea664d7bd9670bfee\versioneer.py", line 1412, in get_versions  
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\RobertMetcalf\AppData\Local\Temp\pip-install-nx4om0m6\ellucianethospythonclient_c34c911c0cc54dbea664d7bd9670bfee\versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

```

**Comment by rmetcalf9** [comment]
According to 
https://github.com/python-versioneer/python-versioneer/blob/bdf701a688a410659a42c49cab6bd901389743d6/NEWS.md?plain=1#L3
Versioneer suppoerts python 3.12 in versioneer version 0.30. Currently pypi only has only 0.29
https://pypi.org/project/versioneer/
